version: '3'

services:
  postgres:
    container_name: postgres
    restart: always
    image: postgres:13.0-alpine
    ports:
      - "5432:5432"
    environment:
      - DEBUG=false
      - POSTGRES_DB=blog
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=admin
      - POSTGRES_URL=jdbc:postgresql://0.0.0.0:5432/blog
    volumes:
      - ./project/migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
  redis:
    container_name: redis
    restart: always
    image: redis:6.2.0
    ports:
      - "6379:6379"
    environment:
      - DEBUG=false
  postgres_test:
    container_name: postgres_test
    restart: always
    image: postgres:13.0-alpine
    ports:
      - "5433:5432"
    environment:
      - DEBUG=false
      - POSTGRES_DB=blog
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=admin
      - POSTGRES_URL=jdbc:postgresql://0.0.0.0:5433/blog
    volumes:
      - ./project/migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
  redis_test:
    container_name: redis_test
    restart: always
    image: redis:6.2.0
    ports:
      - "6380:6379"
    environment:
      - DEBUG=false
