version: '3'

services:
  postgres:
    container_name: postgres
    restart: always
    image: postgres:13.0-alpine
    ports:
      - "5432:5432"
    environment:
      - DEBUG=false
      - POSTGRES_DB=blog
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=admin
    volumes:
      - ./project/migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
  redis:
    container_name: redis
    restart: always
    image: redis:6.2.0
    ports:
      - "6379:6379"
    environment:
      - DEBUG=false
